### ISSUE TITLE
Rules are not visible through the BIG-IP GUI

### ISSUE THREAD

**Issue by dramich** [f5devcentral/f5-cccl#152]
When creating a policy with rules the rule names show up under the policy but when clicking the rule name an error occurs `Object not found - 0` 

This appears to be caused by creating the rule with the name formatted as `/partition/name`. 
If the rule is created without the partition in the name the GUI works as expected. 

`"name": "/partition/0",`
`"name": "0",`

**Comment by richbrowne** [comment]
Dan,

  Is this an issue with the new CCCL?  It might be since some of the logic you implemented was brought forward.

Rich

**Comment by dramich** [comment]
It is with the new CCCL, it was discovered when the uplift was being done for cf. K8's also has the same issue now.
