### ISSUE TITLE
CCCL incompatible with BIG-IP v11.6.1 policies

### ISSUE THREAD

**Issue by f5gary** [f5devcentral/f5-cccl#167]
CCCL fails when running against BIG-IP v11.6.1 with the following error:
`
2017/10/09 21:20:29 [INFO] [2017-10-09 21:20:29,974 f5_cccl.resource.resource INFO] Creating ApiPolicy: /test/openshift_insecure_routes
2017/10/09 21:20:30 [ERROR] [2017-10-09 21:20:30,149 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(ApiPolicy) /test/openshift_insecure_routes.
2017/10/09 21:20:30 [ERROR] [2017-10-09 21:20:30,150 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://172.16.2.3:443/mgmt/tm/ltm/policy/
2017/10/09 21:20:30 [INFO] Text: u'{"code":400,"message":"Found unexpected json pair at configuration item /ltm/policy/~test~openshift_insecure_routes/rules/openshift_route_default_foo-com. The json pair is \\"description\\":null.","errorStack":[]}'
`

The description field was added in commit 8f6de75, and that's when I started to see this error.

**Comment by edarzins** [comment]
Fixed via https://github.com/f5devcentral/f5-cccl/pull/172
