### ISSUE TITLE
Ability to set User-Agent

### ISSUE THREAD

**Issue by amudukutore** [f5devcentral/f5-cccl#170]
Add the ability to set the User-Agent on the HTTP connection to the BIG-IP. This will allow users of CCCL set a customized User-Agent, which can then later be retrieved via BIG-IP logs to identify the client type.

**Comment by edarzins** [comment]
iControl REST already has a function to set the User-Agent for a session: append_user_agent(). Controllers can use this function directly, so there's no need to add this functionality to CCCL.

**Comment by edarzins** [comment]
https://github.com/f5devcentral/f5-cccl/commit/a9f6920f0e114332106afaa2e43c5f7cc0b9e29c
