### ISSUE TITLE
Duplicate key error with iRule containing partition

### ISSUE THREAD

**Issue by dramich** [f5devcentral/f5-cccl#175]
When passing in a config that includes an iRule following the cccl schema, cccl returns a duplicate key error for the partition. It appears to not be filtering the top level partition and the in object partition. 
`"resources": {
    "cf": {
      "iRules": [{
        "name": "forward_to_vip",
        "partition": "cf",
        "apiAnonymous": "do stuff"
      }]
    }
  }`

**Comment by edarzins** [comment]
This is a bug in the schema, the partition in the iRule is redundant and needs to be removed.

**Comment by dramich** [comment]
Fixed in pr #178
