### ISSUE TITLE
Loading _f5.py causes import errors

### ISSUE THREAD

**Issue by dramich** [f5devcentral/f5-cccl#48]
running from f5_cccl._f5 import CloudBigIP from a python interpreter causes import errors

>>> from f5_cccl._f5 import CloudBigIP
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    from f5_cccl._f5 import CloudBigIP
  File "/usr/local/lib/python3.5/site-packages/f5_cccl/_f5.py", line 38, in <module>
    from common import list_diff, list_intersect
  File "/Users/ramich/development/f5-cccl/f5_cccl/common.py", line 26, in <module>
    import jwt
ImportError: No module named 'jwt'

From interpreter tried to import jwt and it still failed. Possibly requirements file needs to be update.

**Comment by michaeldayreads** [comment]
@dramich - Attempting to replicate this - with a new virtualenv, from f5-cccl base dir did:

```
pip install .
python
>>> from f5_cccl._f5 import CloudBigIP
```
and did not get an error?

Could you share a bit more information on your workflow to help me replicate?

**Comment by dramich** [comment]
I am pip installing it using 
`pip install -e git+https://github.com/dramich/f5-cccl.git@1f85ec9fbe65fbdbd01963969c94b45e83b57b8a#egg=f5_cccl`

**Comment by michaeldayreads** [comment]
That is definitely helpful @dramich, thanks.

Reasonably confident this is a consequence of python 2 and 3 both being present on mac, and the need to explicitly either install to `python3` using `pip3` or to create a python 3 ve with `virtualenv -p python3 path/to/ve/files`.

Without the `-p python3` even within the virtualenv, python3 still points to the local install of python3, i.e:

```
virtualenv ../ve/issue-48-v2
. ../ve/issue-48-v2/bin/activate
which python3
> /usr/local/bin/python3
```

vs 

```
virtualenv -p python3 ../ve/issue-48-v3
. ../ve/issue-48-v3/bin/activate
which python3
> /Users/day/0_deck_dojo/ve/issue-48-v3/bin/python3
```

In actual use, the install from egg and setup would be to one environment, not split as we are encountering with virtualenv.
